// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoXIiWV87_PwGlPo-G8In6HtjheKSZizg',
    appId: '1:373482043990:web:887284b6713be1703e19f7',
    messagingSenderId: '373482043990',
    projectId: 'kaong-fermentation-app',
    authDomain: 'kaong-fermentation-app.firebaseapp.com',
    storageBucket: 'kaong-fermentation-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRq-Dd3RQDOCdhf36T-1E3Bo4ITT5otR0',
    appId: '1:373482043990:android:d49f95e27cc85d973e19f7',
    messagingSenderId: '373482043990',
    projectId: 'kaong-fermentation-app',
    storageBucket: 'kaong-fermentation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDaOEOk2JEKZxxvyD-tWc1Noa98Ma6Jc',
    appId: '1:373482043990:ios:b8a0e040af4189da3e19f7',
    messagingSenderId: '373482043990',
    projectId: 'kaong-fermentation-app',
    storageBucket: 'kaong-fermentation-app.firebasestorage.app',
    iosBundleId: 'com.example.kaongFermentationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKDaOEOk2JEKZxxvyD-tWc1Noa98Ma6Jc',
    appId: '1:373482043990:ios:b8a0e040af4189da3e19f7',
    messagingSenderId: '373482043990',
    projectId: 'kaong-fermentation-app',
    storageBucket: 'kaong-fermentation-app.firebasestorage.app',
    iosBundleId: 'com.example.kaongFermentationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoXIiWV87_PwGlPo-G8In6HtjheKSZizg',
    appId: '1:373482043990:web:be896f2354954e6c3e19f7',
    messagingSenderId: '373482043990',
    projectId: 'kaong-fermentation-app',
    authDomain: 'kaong-fermentation-app.firebaseapp.com',
    storageBucket: 'kaong-fermentation-app.firebasestorage.app',
  );
}
