import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI
import 'theme/app_theme.dart';
import 'ui/screens/dashboard_screen.dart';

void main() async {
  // 1. Ensure Flutter bindings are initialized first
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase
  // If this line gives you an error, you haven't run 'flutterfire configure' yet.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the App
  runApp(const KaongBrewingApp());
}

class KaongBrewingApp extends StatelessWidget {
  const KaongBrewingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Kaong Fermentation Monitor',
      debugShowCheckedModeBanner: false, // Removes the "Debug" banner
      
      // Apply the Custom Theme we created earlier
      theme: AppTheme.lightTheme,
      
      // Set the starting screen
      home: const DashboardScreen(),
    );
  }
}